### ISSUE TITLE
IndexError: Cannot choose from an empty sequence with 100 ants

### ISSUE THREAD

**Issue by darless** [riiswa/colony-ant-simulator#7]
```
Enter the number of ants you want for the simulation (recommended: 10-100) : 100
Traceback (most recent call last):
  File "colony_ant_simulator.py", line 316, in <module>
    Environment(nb_ant)
  File "colony_ant_simulator.py", line 130, in __init__
    1, f_move(self.environment, self.ant_data, self.food))
  File "colony_ant_simulator.py", line 266, in f_move
    coord = choice(dont_out(ant))
  File "/usr/lib/python3.8/random.py", line 290, in choice
    raise IndexError('Cannot choose from an empty sequence') from None
IndexError: Cannot choose from an empty sequence
```

**Comment by HangryBear** [comment]
Hi, I believe I have fixed this bug, and have submitted a pull request with the updated code. Hope this fixes the problem for you.

**Comment by riiswa** [comment]
Thanks!
